version: '2'
services:
    demon-app:
        image: demon
        external_links:
            - demon-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/demon?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    demon-mysql:
        extends:
            file: mysql.yml
            service: demon-mysql
